#!/usr/bin/env bash
# build-inline-runtime.sh
# Generates dist/v0-runtime-inline.html — a self-contained inline deployment
# artefact for Bandzoogle Headers & Metatags.
#
# Inlines both data files as JS object literals in window.GYPSY_CONFIG and
# both renderer modules verbatim. No external fetch required at runtime.
#
# Usage: run from the project root
#   ./scripts/build-inline-runtime.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUT="$PROJECT_ROOT/dist/v0-runtime-inline.html"

REVIEWS_JSON="$PROJECT_ROOT/data/reviews.json"
SHOWS_JSON="$PROJECT_ROOT/data/shows.json"
REVIEWS_JS="$PROJECT_ROOT/js/reviews.js"
SHOWS_JS="$PROJECT_ROOT/js/shows.js"

# Verify source files exist
for FILE in "$REVIEWS_JSON" "$SHOWS_JSON" "$REVIEWS_JS" "$SHOWS_JS"; do
  if [[ ! -f "$FILE" ]]; then
    echo "ERROR: source file not found: $FILE" >&2
    exit 1
  fi
done

# Check for </script> in any source file — would break inline HTML
FOUND_CLOSE=false
for FILE in "$REVIEWS_JSON" "$SHOWS_JSON" "$REVIEWS_JS" "$SHOWS_JS"; do
  if grep -qF '</script>' "$FILE"; then
    echo "ERROR: source file contains '</script>': $(basename "$FILE")" >&2
    echo "       Escape all occurrences to '<\\/script>' before running this script." >&2
    FOUND_CLOSE=true
  fi
done
if $FOUND_CLOSE; then
  exit 1
fi

TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%S UTC")"

mkdir -p "$PROJECT_ROOT/dist"

# Build the GYPSY_CONFIG block using Python for clean JSON formatting.
# json.dumps regenerates the JSON with consistent 2-space indentation.
# Each JSON value's first line ({) is placed inline with the property name;
# subsequent lines get 4 extra spaces to align under the opening brace.
CONFIG_BLOCK=$(python3 - "$REVIEWS_JSON" "$SHOWS_JSON" <<'PYEOF'
import json, sys

with open(sys.argv[1]) as f:
    reviews = json.load(f)
with open(sys.argv[2]) as f:
    shows = json.load(f)

def format_value(obj, base_indent):
    """Serialize obj to indented JSON. First line goes inline; rest get base_indent spaces."""
    raw = json.dumps(obj, indent=2)
    lines = raw.split('\n')
    result = [lines[0]]
    for line in lines[1:]:
        result.append(' ' * base_indent + line)
    return '\n'.join(result)

reviews_fmt = format_value(reviews, 4)
shows_fmt   = format_value(shows,   4)

print('  window.GYPSY_CONFIG = {')
print('    reviewsData: ' + reviews_fmt + ',')
print('    showsData:   ' + shows_fmt)
print('  };')
PYEOF
)

{
  cat <<EOF
<!-- ============================================================
     v0 RUNTIME — INLINE DEPLOYMENT ARTEFACT
     Generated: $TIMESTAMP
     Source files: data/reviews.json, data/shows.json,
                   js/reviews.js, js/shows.js

     Paste into Bandzoogle: Pages → Site-wide Settings → Headers & Metatags
     Place AFTER fonts, WA CDN, FA Pro Kit tags.

     DO NOT edit this file directly. Regenerate by running
     scripts/build-inline-runtime.sh from the project root.
     ============================================================ -->

<script>
$CONFIG_BLOCK
</script>

EOF

  printf '<script>\n'
  cat "$REVIEWS_JS"
  printf '</script>\n\n'

  printf '<script>\n'
  cat "$SHOWS_JS"
  printf '</script>\n'

} > "$OUT"

BYTE_SIZE=$(wc -c < "$OUT" | tr -d ' ')
LINE_COUNT=$(wc -l < "$OUT" | tr -d ' ')

echo "Built: dist/v0-runtime-inline.html"
echo "Lines: $LINE_COUNT"
echo "Bytes: $BYTE_SIZE"
echo "</script> escape check: PASSED (no occurrences found in source files)"
