#!/usr/bin/env bash
# build-v0-bundle.sh
# Concatenates the v0 CSS source files into a single deployment bundle
# for pasting into Bandzoogle → Design → Customize CSS.
#
# Usage: run from the project root
#   ./scripts/build-v0-bundle.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUT="$PROJECT_ROOT/dist/v0-bundle.css"

# Source files in import order (mirrors v0.css @import sequence)
SOURCES=(
  "css/variables.css"
  "css/components/icons.css"
  "css/components/typography.css"
  "css/components/navigation.css"
  "css/components/footer.css"
  "css/components/reviews.css"
  "css/components/buttons-v0.css"
  "css/components/homepage.css"
  "css/components/page-hero.css"
  "css/components/press-kit.css"
  "css/components/press-photos.css"
  "css/components/contact.css"
  "css/components/shows.css"
  "css/components/videos.css"
  "css/components/blog.css"
  "css/components/cult-membership.css"
  "css/components/section-rhythm.css"
  "css/components/merch-store.css"
)

TIMESTAMP="$(date -u +"%Y-%m-%d %H:%M UTC")"

mkdir -p "$PROJECT_ROOT/dist"

# Write header comment block
cat > "$OUT" <<EOF
/* ============================================================
   Gypsy Pistoleros — v0.css site-wide bundle
   Generated from css/v0.css source files
   Paste into Bandzoogle: Design → Customize CSS

   Do NOT edit this file directly — edit the source files in
   css/ and rerun scripts/build-v0-bundle.sh
   Generated: $TIMESTAMP
   ============================================================ */

EOF

STRIPPED_IMPORTS=()

for REL_PATH in "${SOURCES[@]}"; do
  ABS_PATH="$PROJECT_ROOT/$REL_PATH"

  if [[ ! -f "$ABS_PATH" ]]; then
    echo "ERROR: source file not found: $REL_PATH" >&2
    exit 1
  fi

  # Separator comment
  cat >> "$OUT" <<EOF
/* ========================================
   $REL_PATH
   ======================================== */
EOF

  # Append file content, stripping any @import lines
  while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*@import ]]; then
      STRIPPED_IMPORTS+=("$REL_PATH: $line")
    else
      printf '%s\n' "$line" >> "$OUT"
    fi
  done < "$ABS_PATH"

  # Blank line between sections
  echo "" >> "$OUT"
done

# Report
BYTE_SIZE=$(wc -c < "$OUT" | tr -d ' ')
LINE_COUNT=$(wc -l < "$OUT" | tr -d ' ')

echo "Built: dist/v0-bundle.css"
echo "Lines: $LINE_COUNT"
echo "Bytes: $BYTE_SIZE"

if [[ ${#STRIPPED_IMPORTS[@]} -gt 0 ]]; then
  echo ""
  echo "Stripped @import lines (${#STRIPPED_IMPORTS[@]}):"
  for ENTRY in "${STRIPPED_IMPORTS[@]}"; do
    echo "  $ENTRY"
  done
else
  echo "Stripped @import lines: none"
fi
